name: bmi_calculator
description: A new Flutter project.
version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.5.5+1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: SF Pro Display
      fonts:
        - asset: fonts/SF-Pro-Display-Ultralight.otf
          weight: 100
        - asset: fonts/SF-Pro-Display-Thin.otf
          weight: 200
        - asset: fonts/SF-Pro-Display-Light.otf
          weight: 300
        - asset: fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: fonts/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: fonts/SF-Pro-Display-Heavy.otf
          weight: 800
        - asset: fonts/SF-Pro-Display-Black.otf
          weight: 900
